import uuid
from datetime import datetime

class FHIRBridge:
    @staticmethod
    def create_lab_order(patient_id, test_name):
        """
        Generates a 2026-compliant HL7 FHIR ServiceRequest.
        Updated to match main.py requirements perfectly.
        """
        return {
            "resourceType": "ServiceRequest",
            "id": str(uuid.uuid4()),
            "status": "active",
            "intent": "order",
            "priority": "routine",
            "subject": {"reference": f"Patient/{patient_id}"},
            "authoredOn": datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "display": str(test_name)
                }],
                "text": str(test_name)
            },
            "note": [{"text": "Generated by Cura AI Agentic Workflow"}]
        }